In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [97]:
np.__version__

'1.21.2'

In [98]:

pd.__version__

'1.3.5'

In [9]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-02-05 10:24:06--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.1’

data.csv.1          100%[===================>]   1.41M   421KB/s    in 3.4s    

2022-02-05 10:24:11 (421 KB/s) - ‘data.csv.1’ saved [1475504/1475504]



In [99]:
data = pd.read_csv('data.csv')

In [181]:
data.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [101]:
data_bmw = data[data['Make'] == 'BMW']
data_bmw.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [102]:
data_bmw['MSRP'].mean()

61546.76347305389

In [103]:
data_2015 = data[data['Year'] >= 2015]
data_2015.head(2)

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   

   Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32     Performance      Compact   Convertible           35        26   
33     Performance      Compact   Convertible           35        26   

    Popularity   MSRP  
32         819  27495  
33         819  24995

In [104]:
#data_2015.isnull().count()

In [105]:
data_2015.groupby(['Year'])['Engine HP'].apply(lambda x: x.isnull().count())#.mean()#to_frame()

Year
2015    2170
2016    2157
2017    1668
Name: Engine HP, dtype: int64

In [106]:
#data_2015.groupby(['Year'])['Engine HP'].apply(lambda x: x.isnull().sum()).mean()

In [107]:
data_2015.groupby(['Year'])['Engine HP'].mean()#apply(lambda x: x.isnull().sum())#.mean()

Year
2015    270.965181
2016    273.768007
2017    274.615012
Name: Engine HP, dtype: float64

In [108]:
data_2015['Engine HP'].isna().sum()

51

In [109]:
mean_hp_before = data['Engine HP'].mean()
mean_hp_before

249.38607007176023

In [110]:
mean_hp_after = data['Engine HP'].fillna(mean_hp_before).mean()

In [111]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


In [112]:
data_style = data[data['Make'] == "Rolls-Royce"]
data_style.head(1)

Make     Model  Year             Engine Fuel Type  Engine HP  \
2921  Rolls-Royce  Corniche  2001  premium unleaded (required)      325.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
2921               8.0         AUTOMATIC  rear wheel drive              2.0   

     Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
2921   Exotic,Luxury        Large   Convertible           15        10   

      Popularity    MSRP  
2921          86  359990

In [163]:
data_col = data_style[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [164]:
data_col = data_col.drop_duplicates()

In [165]:
x = data_col.values
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [166]:
#xTx = x.dot(x.T)
#xTx

In [170]:
xTx = x.T.dot(x)
xTx

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [171]:
in_xTx = np.linalg.inv(xTx)
in_xTx

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [172]:
in_xTx.sum()

0.032212320677486195

In [157]:
#xTx

In [158]:
#in_xTx = np.linalg.inv(xTx)
#in_xTx

In [173]:
#in_xTx.sum()

In [174]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [175]:
#in_xTx.dot(x.T)

In [179]:
w = in_xTx.dot(x.T).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

The first value of 

In [180]:
w[0]

0.19989598183186175